Set Working Default Models in HF Parsers
# Set Working Default Models in HF Parsers

The default model parsers for AST and TTS don't work:
- For ASR, `openai/whisper-large-v3` just throws 500 errors (even on the model card in HF)
- For TTS, `suno/bark` requires a HF PRO subscription to run

For now, we can just default to the next-best models for those tasks (based on like count) which support remote inference

## Testing:
- Build the hf extension following its README
- Update aiconfig/cookbooks/Gradio/aiconfig_model_registry.py to have the tts and asr remote parsers added (should register all remote ones by default there?)
```
(aiconfig) ryanholinshead@Ryans-MBP aiconfig % parsers_path=/Users/ryanholinshead/Projects/aiconfig/cookbooks/Gradio/aiconfig_model_registry.py
(aiconfig) ryanholinshead@Ryans-MBP aiconfig % aiconfig edit --server-mode=debug_servers --parsers-module-path=$parsers_path
```

Ensure the model defaults work:
<img width="1479" alt="Screenshot 2024-02-13 at 11 25 38 AM" src="https://github.com/lastmile-ai/aiconfig/assets/5060851/4bc7c3a8-c251-47df-87c3-11e1077bb61e">
<img width="1465" alt="Screenshot 2024-02-13 at 11 26 42 AM" src="https://github.com/lastmile-ai/aiconfig/assets/5060851/98697b09-3cf6-4a83-83e2-b8930f4a97ef">


Note, was getting an error using the travel.aiconfig.json config
```
(aiconfig) ryanholinshead@Ryans-MBP aiconfig % aiconfig edit --aiconfig-path=$aiconfig_path --server-mode=debug_servers --parsers-module-path=$parsers_path

 File "/Users/ryanholinshead/Projects/aiconfig/python/src/aiconfig/Config.py", line 138, in load_json
    update_model_parser_registry_with_config_runtime(config_runtime)
  File "/Users/ryanholinshead/Projects/aiconfig/python/src/aiconfig/registry.py", line 134, in update_model_parser_registry_with_config_runtime
    retrieved_model_parser = ModelParserRegistry.get_model_parser(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryanholinshead/Projects/aiconfig/python/src/aiconfig/registry.py", line 64, in get_model_parser
    return ModelParserRegistry._parsers[model_id]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'HuggingFaceImage2TextTransformer'
```