Run python autoformatter on entire Python libraries
I just got tired of doing this manually every time. We should just eventually make a script to do this, can do later. Filed a task: https://github.com/lastmile-ai/aiconfig/issues/771

This includes the cookbooks

cc jonathan I couldn't just do a clean

```
fd --glob '*.py'  cookbooks/* | xargs python -m 'scripts.lint' --mode=fix --files
```

because there's an issue with llama extension:
```
rossdancraig@Rossdans-MBP aiconfig % fd --glob '*.py'  cookbooks/llama | xargs python -m 'scripts.lint' --mode=fix --files
Running autoflake
[Errno 2] No such file or directory: '/Users/jonathan/Projects/aiconfig/extensions/llama/python/llama.py'
Running isort
Broken 1 paths
Running black
Usage: black [OPTIONS] SRC ...
Try 'black -h' for help.

Error: Invalid value for 'SRC ...': Path '/Users/jonathan/Projects/aiconfig/extensions/llama/python/llama.py' does not exist.
[CRITICAL] 2024-01-05 01:58:04,022 lint.py:161: err: Some jobs failed:
OK:Oks:
Ok
stdout=''
stderr=''
Err:Errs:
Failure: exit code = 1
stdout=''
stderr=''
Failure: exit code = 2
stdout=''
stderr=''

```