Change typo in huggingface-hub imports, remove pinned deps from llama-guard
Got some issues before:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiconfig-extension-llama-guard 0.0.2 requires torch==2.1.0, but you have torch 2.1.2 which is incompatible.
aiconfig-extension-llama-guard 0.0.2 requires transformers==4.35.2, but you have transformers 4.36.2 which is incompatible.
```

Which are now fixed.


Also the `huggingface_hub` lib package uses hypen, not underscore: https://pypi.org/project/huggingface-hub/